var problemTwoButton = document.querySelector("#calc-2")


problemTwoButton.addEventListener("click",function(){

    // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    let result = 0

    let previous = 0; // the term previous
    let current = 1; // the current term
    let next  = 0; // the new term
    while(current < 4000000){
        // get the next number
        next = previous + current;
        previous = current;
        current = next;

        // check it's even and less than 4m
        if(current % 2 === 0 && current < 4000000){
            result += current;
        };

    };
    // return result;

    document.querySelector("#answer-2").innerHTML = "Answer = " + result
})
